// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0U6ClPssswpVU3Hy7w43Yk-B6bsd-jgk',
    appId: '1:583799656188:web:4eda6364db1768fdd89179',
    messagingSenderId: '583799656188',
    projectId: 'elmore-84d12',
    authDomain: 'elmore-84d12.firebaseapp.com',
    storageBucket: 'elmore-84d12.appspot.com',
    measurementId: 'G-013GE3L3YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-GSCOCmd-4m74L2sz1J0jG_E8hGmghws',
    appId: '1:583799656188:android:6b35e9210e116683d89179',
    messagingSenderId: '583799656188',
    projectId: 'elmore-84d12',
    storageBucket: 'elmore-84d12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqJMhpg944kJSOZu58ldjtcRofdepeV5w',
    appId: '1:583799656188:ios:3384ef3472391c5fd89179',
    messagingSenderId: '583799656188',
    projectId: 'elmore-84d12',
    storageBucket: 'elmore-84d12.appspot.com',
    iosBundleId: 'com.example.elmore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqJMhpg944kJSOZu58ldjtcRofdepeV5w',
    appId: '1:583799656188:ios:3384ef3472391c5fd89179',
    messagingSenderId: '583799656188',
    projectId: 'elmore-84d12',
    storageBucket: 'elmore-84d12.appspot.com',
    iosBundleId: 'com.example.elmore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0U6ClPssswpVU3Hy7w43Yk-B6bsd-jgk',
    appId: '1:583799656188:web:baaa36066e378647d89179',
    messagingSenderId: '583799656188',
    projectId: 'elmore-84d12',
    authDomain: 'elmore-84d12.firebaseapp.com',
    storageBucket: 'elmore-84d12.appspot.com',
    measurementId: 'G-P9M6RT7TXX',
  );

}